<?php

namespace App\Framework;

use App\Storage\Storage;
use Exception;

class Entity implements EntityInterface
{   public  static string $table_name = 'contract';

    protected static array $fillable = [];
    protected static array $readonly = [];
    protected static array $relations = [];


    public function __construct()
    {


    }
    public static function filable() {
        return static::$fillable;
    }
    public static function readonly() {
        return static::$readonly;
    }

    static function getTableName() {

        return static::$table_name; //$table_name;
    }

    public static function getEntity($class, $id)
    {
        $class='\App\Entities\\' . ucfirst(strtolower($class) );
        $entity = $class::get($id);
        return $entity;
//        return $entity->toArray();
    }

    protected static function generateAccessor($fieldName,$action='set') {
        // Split the field name by underscores
        $parts = explode('_', $fieldName);

        // Capitalize each part except the first one
        $getterName = 'set' . ucfirst(array_shift($parts));
        foreach ($parts as $part) {
            $getterName .= ucfirst($part);
        }

        return $getterName;
    }


    public function  setVar($name, $value)
    {
        if(in_array($name ,static::$fillable)) {
            $this->$name = $value;
        }
    }
    public function getVar($name)
    {
        if(in_array($name ,static::$fillable)) {
            return $this->$name??null;
        }
    }


    public function __isset($name)
    {
        return isset($this->$name);
    }


    public static function makeFromArray($array)
    {



        $class_name =  static::class;

        ///$object= new $class_name();
//        if(isset($array['id'])){
//            $object = $class_name::get($array['id']);
//        }else{
//            $object= new $class_name();
//        }
        $object= new $class_name();
//        return $object;
//
//        dd($class_name);
//        return $class_name;
//
//
//
//        trace($class_name);
//        trace($array);
//        trace($object);



        foreach(static::$fillable as $key  ){
            if(isset($array[$key])){

//                $setter_name = self::generateAccessor($key,'set');
//                $object->$setter_name($array[$key]);
                $object->setVar( $key , $array[$key]);

            }
        }
        return $object;
    }

    public static function updateFromArray($object, $array)
    {
        //$class_name =  static::class;
       // $object= new $class_name();
//        trace($object);
//        trace($array);
        foreach(static::$fillable as $key  ){
            if(isset($array[$key])){
//                $setter_name = self::generateAccessor($key,'set');
//                $object->$setter_name($array[$key]);
               // trace("\$object->setVar( $key , \$array[$key]);");

                $object->setVar( $key , $array[$key]);
            }
        }
        return $object;

    }

    protected $id= null;

    public function getId()
    {
        return $this->id;
    }

    protected function setId($id): void
    {
        $this->id = $id;
    }


    public   function getCreatedAt()
    {
        return  $this->created_at??null;
    }

    public   function getUpdatedAt()
    {
        return $this->updated_at??null;
    }

    public function toArray(): array
    {
      //  return (array)$this;
        return get_object_vars($this);
    }

    public function __toString(): string
    {
        return json_encode($this->toArray());
    }



    public function save(): void
    {
        $id = Storage::save($this);
        if($id && !$this->getId() ){
            $this->setId($id);
        }
   }


    public static function get($id): object
    {
        return static::findByID($id);
    }

    public static function findByID($id): object
    {
        $oo= Storage::findByID(static::class, $id);
        //dd($oo);
        return $oo;
    }


    public static function findFirst(array $criteria): object
    {
        return Storage::find(static::class, $criteria);
    }


    public static function find(array $criteria=[]): array
    {

        return Storage::find(static::class, $criteria);
   }

    public static function delete()
    {

        throw new Exception ('not implemented');
    }


    /**
     * @return array
     */
    public static function getRelations(): array
    {
        return get_called_class()::$relations;
    }

    public function loadRelations($key= null)
    {
        // parent::loadRelations(); // TODO: Change the autogenerated stub

//        protected static array $relations = [
//            "contracts" => [
//                'type' => 'hasMany'
//                , 'local' => 'id'
//                , 'references' => 'App\Entities\Contract.customer_id'
//            ]
//        ];

        foreach (static::$relations as $name => $rel) {


            if($key && $key !== $name){
                continue;
            }
            $rel = (object)$rel;
            $ref = explode('.', $rel->references);
            $class = $ref[0];
            $field = $ref[1];

            $local_field = $rel->local;
            $getter = 'get' . ucfirst($local_field);

            switch ($rel->type) {
                case 'hasOne':
                    $this->references[$name] = Storage::find($class, [$field => $this->$getter()]);
                    break;
                case 'hasMany':
                default:
                    //$this->references[$name] = Storage::find($class, [$field => $this->$getter()]);
                    return Storage::find($class, [$field => $this->$getter()]);
                    break;

            }

        }

    }




}